sudo: required
services:
  - docker

before_install:
  - docker build -t mleu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mleu/react-test npm test -- --coverage

after_success:
  - docker build -t mleu/multi-client ./client
  - docker build -t mleu/multi-nginx ./nginx
  - docker build -t mleu/multi-server ./server
  - docker build -t mleu/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push mleu/multi-client
  - docker push mleu/multi-nginx 
  - docker push mleu/multi-server
  - docker push mleu/multi-worker